version: '2.3'

services:
  opennodes_postgres:
    restart: always
    container_name: opennodes-postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: opennodes
      POSTGRES_PASSWORD: "${DB_PASS}"
    volumes:
      - ./postgres/lib:/var/lib/postgresql
      - ./postgres/data:/var/lib/postgresql/data
    mem_limit: 2g
    memswap_limit: 3g
    ports:
      - "127.0.0.1:5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
  opennodes_crawler:
    restart: always
    depends_on:
      - opennodes_postgres
    container_name: opennodes-crawler
    build:
      context: ""
      dockerfile: Dockerfile
    volumes:
      - ./static:/static
      - ./geoip:/geoip
      - ./db_cache:/db_cache
    entrypoint:
      - python
      - crawler.py
      - --daemon
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
  opennodes_site:
    restart: always
    depends_on:
      - opennodes_postgres
      - opennodes_dashd
    container_name: opennodes-site
    build:
      context: ""
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./static:/static
      - ./geoip:/geoip
    entrypoint:
      - python
      - server.py
      - --prod
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
  opennodes_dashd:
    restart: always
    container_name: opennodes-dashd
    build: https://github.com/dashpay/docker-dashd.git
    ports:
      - "9999:9999"
      - "127.0.0.1:9998:9998"
    volumes:
      - ./dash:/dash
    environment:
      DISABLEWALLET: 1
      PRINTTOCONSOLE: 1
      RPCUSER: myrpcuser
      RPCPASSWORD: myrpcpassword
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
  opennodes_tor:
    restart: always
    container_name: opennodes-tor
    image: dperson/torproxy
    ports:
      - "127.0.0.1:9050:9050"
      - "8118:8118"
  opennodes_ipv6nat:
    restart: always
    container_name: opennodes-ipv6nat
    image: robbertkl/ipv6nat
    network_mode: "host"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro


